#!/bin/bash
set -uo pipefail

sed -i.bak "s/\"version\"\: \"0.0.1\"/\"version\"\: \"$SEMVER\"/g" package.json

npm run check-types
npm run lint
node esbuild.js --production

./node_modules/.bin/vsce package
