#!/bin/bash
set -euo pipefail

if [ -z "$O_V_T" ]; then
  echo "Error: O_V_T missing."
  exit 1
fi

if [ -z "$V_M_T" ]; then
  echo "Error: V_M_T missing."
  exit 1
fi

VSIX_FILE=$(ls *.vsix | head -n 1)
OVSX_STORE=file

echo ""
echo "..starting ovsx"

./node_modules/.bin/ovsx publish "$VSIX_FILE" --registryUrl https://open-vsx.org -p "$O_V_T"

echo ""
echo "ovsx done."
sleep 2
echo ""
echo "..starting vsce"

./node_modules/.bin/vsce publish -p "$V_M_T" --packagePath "$VSIX_FILE"

echo ""
echo "vsce done."
